apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cltl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cltl
    app.kubernetes.io/part-of: tkrw-pr712-0075-0069-app
  name: devfile-sample-cltl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cltl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cltl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-cltl@sha256:fc09a3a1aa6341a2d8b6914514fbfdb92028cebcd1a5f22bc5265f4cb6afd4ed
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
